name: Workflow to Create an Azure VM.

on: push

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions

# Set up a service principal using
#
# az login --tenant gerardjgormangmail.onmicrosoft.com
# rg=$(az group create --location uksouth --name GpuCI --query id | xargs)
# az ad sp create-for-rbac --name "http://GpuCI" --role contributor --scopes $rg --sdk-auth
#
# This will output some JSON which you should add to your GitHub repository as a secret called "AZURE_CREDENTIALS"
# 2. Change these variables for your configuration:
env:
  AZURE_RESOURCE_GROUP: GpuCI   # set this to your Azure Resource group's name
  # AZURE_VM_NAME: GpuVM-$GITHUB_SHA
  AZURE_VM_NAME: GpuVM
  # AZURE_VM_SIZE: NC6_Promo
  AZURE_VM_SIZE: Standard_DS2_v2

jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

   # Authentication
    - uses: azure/login@v1
      with:
        azcliversion: latest
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Provision a new VM
    - name: Azure CLI script to create a new VM
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "Creating VM"
          az vm create --name ${{ env.AZURE_VM_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --image UbuntuLTS --size ${{ env.AZURE_VM_SIZE }} --admin-username gpuciadmin --generate-ssh-keys --ephemeral-os-disk true
          echo "Running remote script"
          ls -alh $GITHUB_WORKSPACE/.github/scripts/azure_gpu.sh
          chmod a+x $GITHUB_WORKSPACE/.github/scripts/azure_gpu.sh
          az vm run-command invoke --name ${{ env.AZURE_VM_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --command-id RunShellScript --scripts @{$GITHUB_WORKSPACE/.github/scripts/azure_gpu.sh} --parameters hello world
          echo "Deleting VM"
          az vm delete --name ${{ env.AZURE_VM_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --yes
          echo "Deleting VM NIC"
          az network nic delete --name ${{ env.AZURE_VM_NAME }}VMNIC --resource-group ${{ env.AZURE_RESOURCE_GROUP }}
          echo "Deleting VM IP"
          az network public-ip delete --name ${{ env.AZURE_VM_NAME }}PublicIP --resource-group ${{ env.AZURE_RESOURCE_GROUP }}
          echo "Deleting NSG"
          az network nsg delete --name ${{ env.AZURE_VM_NAME }}NSG --resource-group ${{ env.AZURE_RESOURCE_GROUP }}
          echo "Deleting VNet"
          az network vnet delete --name ${{ env.AZURE_VM_NAME }}VNET --resource-group ${{ env.AZURE_RESOURCE_GROUP }}


# az vm run-command invoke --name ${{ env.AZURE_VM_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --command-id RunShellScript --scripts 'echo $1 $2' --parameters hello world
